import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.jsx",
    ],
    theme: {
        extend: {
            colors: {
                background: "#f2fcf8",
                "surface-container-highest": "#dbe5e1",
                "surface-tint": "#136a5a",
                "inverse-on-surface": "#e9f3ef",
                "on-error": "#ffffff",
                "on-background": "#141d1b",
                "tertiary-container": "#c6a928",
                "inverse-surface": "#293230",
                "on-primary-fixed-variant": "#005143",
                "secondary-fixed": "#a9eef5",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#00201a",
                "surface-dim": "#d2dcd8",
                "tertiary-fixed-dim": "#e3c543",
                "surface-bright": "#f2fcf8",
                "surface-container-low": "#ecf6f2",
                "primary-container": "#0e6858",
                "error-container": "#ffdad6",
                "on-tertiary-fixed-variant": "#544600",
                "on-secondary-container": "#226c73",
                "secondary-fixed-dim": "#8dd2d9",
                "on-tertiary-container": "#4b3e00",
                "tertiary-fixed": "#ffe16b",
                "on-primary": "#ffffff",
                outline: "#6f7975",
                "on-surface-variant": "#3f4945",
                surface: "#f2fcf8",
                "on-error-container": "#93000a",
                "primary-fixed-dim": "#88d5c1",
                "surface-variant": "#dbe5e1",
                "on-primary-container": "#96e4cf",
                "primary-fixed": "#a4f2dd",
                "on-secondary-fixed": "#002022",
                "inverse-primary": "#88d5c1",
                "secondary-container": "#a6ebf2",
                primary: "#004e41",
                "on-surface": "#141d1b",
                secondary: "#1c686e",
                "on-secondary-fixed-variant": "#004f55",
                "on-tertiary-fixed": "#221b00",
                "outline-variant": "#bec9c4",
                "on-secondary": "#ffffff",
                "surface-container-high": "#e0eae6",
                "on-tertiary": "#ffffff",
                "surface-container": "#e6f0ec",
                error: "#ba1a1a",
                tertiary: "#6f5d00",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                xs: "4px",
                sm: "12px",
                xl: "80px",
                lg: "48px",
                "margin-mobile": "16px",
                gutter: "24px",
                "margin-desktop": "64px",
                base: "8px",
                md: "24px",
            },
            fontFamily: {
                sans: ["Plus Jakarta Sans", ...defaultTheme.fontFamily.sans],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "label-md": ["Plus Jakarta Sans"],
                "label-sm": ["Plus Jakarta Sans"],
                "body-lg": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "headline-xl": ["Plus Jakarta Sans"],
                "title-md": ["Plus Jakarta Sans"],
                "body-md": ["Plus Jakarta Sans"],
            },
            fontSize: {
                "headline-lg-mobile": [
                    "28px",
                    { lineHeight: "36px", fontWeight: "700" },
                ],
                "label-md": [
                    "14px",
                    {
                        lineHeight: "20px",
                        letterSpacing: "0.01em",
                        fontWeight: "600",
                    },
                ],
                "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "headline-lg": [
                    "32px",
                    {
                        lineHeight: "40px",
                        letterSpacing: "-0.01em",
                        fontWeight: "700",
                    },
                ],
                "headline-xl": [
                    "48px",
                    {
                        lineHeight: "56px",
                        letterSpacing: "-0.02em",
                        fontWeight: "700",
                    },
                ],
                "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
            },
        },
    },
    plugins: [forms, containerQueries],
};
